# Setup
title: Sebastian Nickels
url: https://snickels.io
paginate: 1
paginate_path: "/page:num/"
baseurl: "/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sebastian Nickels
#  url: https://twitter.com/mdo
#  email: markdotto@gmail.com

# Custom vars
# version: 3.0.0

# Navbar page list
nav:
  - title: About
    url: /about
    
  - title: Blog
    url: /archive
