# Setup
title: Sebastian Nickels
url: https://snickels.io
#paginate: 1
#paginate_path: "/page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
#  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - _posts
  - archive.md
  - blog.html
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - TEMPLATE_README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options
tracking_enabled: true

# Specify the author for blog posts
author:
  name: Sebastian Nickels
  url: https://snickels.io
#  email: markdotto@gmail.com

# Custom vars
# version: 3.0.0

# Navbar page list
#nav:
#  - title: About
#    url: /
#
#  - title: Blog
#    url: /blog
